def finding_ASCII_Values():
    char=input("type the word:")
    print(ord(char)) 

finding_ASCII_Values()  
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    
finding_ASCII_Values()    

